services:
  - type: web
    name: email-classifier
    env: python
    pythonVersion: 3.10.14
    plan: free
    buildCommand: "./build.sh"
    startCommand: "uvicorn src.app:app --host 0.0.0.0 --port $PORT"
